### ISSUE TITLE
Can not compile with cmake version 3.5.1

### ISSUE THREAD

**Issue by canvanquyen** [schmidh/CPP-Design-Patterns#1]
Hi project owner,

I can't compile your project with cmake.
the log shown as bellow. can you help me to solve this problem. 
Thanks in advance!

On terminal
=======================================================
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   serialization
--   system
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/include  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found C++ REST: /usr/lib/x86_64-linux-gnu/libcpprest.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
CMake Error at CMakeLists.txt:24 (target_compile_features):
  target_compile_features specified unknown feature "cxx_std_14" for target
  "SingleResponsibilityPrinciple".

CMake Error at CMakeLists.txt:27 (target_compile_features):
  target_compile_features specified unknown feature "cxx_std_14" for target
  "OpenClosedPrinciple".

CMakeFiles/CMakeError.log
=======================================================
Run Build Command:"/usr/bin/make" "cmTC_a54e9/fast"
/usr/bin/make -f CMakeFiles/cmTC_a54e9.dir/build.make CMakeFiles/cmTC_a54e9.dir/build
make[1]: Entering directory '/tmp/quyencv/CPP-Design-Patterns/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a54e9.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_a54e9.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_a54e9
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a54e9.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_a54e9.dir/CheckFunctionExists.c.o  -o cmTC_a54e9 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_a54e9.dir/build.make:97: recipe for target 'cmTC_a54e9' failed
make[1]: *** [cmTC_a54e9] Error 1
make[1]: Leaving directory '/tmp/quyencv/CPP-Design-Patterns/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a54e9/fast' failed
make: *** [cmTC_a54e9/fast] Error 2

**Comment by schmidh** [comment]
Please update your C++ compiler.

**Comment by canvanquyen** [comment]
Sorry, that's my mistake.
This bug is the cmake version 3.5 does not support **cxx_std_14**. It is solved by upgrading to version 3.14.

btw : you can update cmake_minimum_required(VERSION 3.0) to cmake_minimum_required(VERSION 3.8) this version supports  **cxx_std_14**

**Comment by schmidh** [comment]
Thank you! Will do it later.

**Comment by schmidh** [comment]
Done. Thank you!
