### ISSUE TITLE
Issue with Mixin Decorator

### ISSUE THREAD

**Issue by ashubhatt** [schmidh/CPP-Design-Patterns#2]
Hello, as mentioned in the example of [Mixin Decorator](https://github.com/schmidh/CPP-Design-Patterns/blame/master/2-Structural/4-Decorator/3-MixinInheritance/mixinDecorator.cpp#L88), the code requires the class to have a default constructor.

An alternate implementation could be that Decorators can accept the Shape Interface as its constructor argument. This way, the actual object construction need not be enclosed in the decorator and the decorators can simply work on the methods exposed by the Shape interface.

Also the decorators themselves can be derived from Shape Interface, so that they can override the virtual methods.

**Comment by schmidh** [comment]
Hi ashubhatt,

interesting comment. What do you want me to do with it?

Kind regards,
Hans

**Comment by ashubhatt** [comment]
Hello @schmidh 

This is just a suggestion. May be you could add another example that shows an improved version of Mixin Decorator which uses Interface as its constructor argument.

**Comment by schmidh** [comment]
I'm always open for PRs. 😀
